################################################################################
#
# Pipeline to process Kodi game -addons
#
################################################################################

#
# Parameters:
#
#   Secret files:
#     * privateKey - the SSH private key used to push to kodi-game repos
#
#   Git authorship:
#     * TODO: Parameterize git authorship
#

trigger:
- master

jobs:
  - job: Build

    pool:
      vmImage: 'ubuntu-20.04'

    strategy:
        matrix:
          Python38:
            python.version: '3.8'

    steps:
    # Download secure file to the agent machine
    - task: DownloadSecureFile@1
      name: privateKey # The name with which to reference the secure file's path on the agent
      displayName: 'Download SSH private key'
      inputs:
        secureFile: 'id_rsa-azure' # The file name or GUID of the secure file

    # Install SSH key prior to a build or deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: "|1|5qWKb7xAKkWXfLw6ZdNAs9FzKNA=|A+W82x1iZWz+nXHgPdlIQmsEOsU= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
        sshKeySecureFile: 'id_rsa-azure'

    - script: |
        dpkg -s libasound2-dev || sudo apt-get install -y libasound2-dev # Required by mame
        dpkg -s libglib2.0-dev || sudo apt-get install -y libglib2.0-dev # Required by fsuae
        dpkg -s libgtk2.0-dev || sudo apt-get install -y libgtk2.0-dev # Required by fsuae
        dpkg -s libpcap-dev || sudo apt-get install -y libpcap-dev # Required by desmume
        dpkg -s mesa-common-dev || sudo apt-get install -y mesa-common-dev # Required by flycast and parallel_n64
      displayName: 'Install system dependencies'

    - script: |
        git config --global user.name "Garrett Brown"
        git config --global user.email "themagnificentmrb@gmail.com"
      displayName: 'Set Git authorship'

    - script: |
        git clone --branch retroplayer-19alpha1 --depth=1 https://github.com/garbear/xbmc.git kodi
      displayName: 'Clone Kodi'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)

    - script: pip install -r requirements.txt
      displayName: 'Install Python requirements'

    - template: azure-process-addon.yml
      parameters:
        # List add-ons in reverse order for sorted results in the kodi-game org
        addons:
          - fsuae
