parameters:
  displayName: ''
  vmImage: ''
  pythonVersion: ''
  dependsOn: ''
  addons: []
  installScript: ''

jobs:
  - job: ${{ parameters.displayName }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: ${{ parameters.dependsOn }}
    strategy:
      matrix:
        Python3:
          python.version: ${{ parameters.pythonVersion }}
    timeoutInMinutes: 0
    steps:
      - template: common-steps.yml
        parameters:
          pythonVersion: ${{ parameters.pythonVersion }}

      # Optional dependency installation script
      - script: |
          sudo apt update
          ${{ parameters.installScript }}
        displayName: 'Install system dependencies'
        condition: ne('${{ parameters.installScript }}', '')

      - template: azure-process-addon.yml
        parameters:
          addons: ${{ parameters.addons }}

      - script: |
          echo
          echo "wiki.txt:"
          echo
          cat game-addons/wiki.txt || true
          echo
        displayName: 'Print wiki.txt'

      - script: |
          echo
          echo "summary.html:"
          echo
          cat game-addons/summary.html || true
          echo
        displayName: 'Print summary.html'
